program =
	vardec [ program ]
	functions [ program ]

exps = { exp ";" } ;

block = '{' exps '}'

exp =
	number
	| float

	| lvalue

	| id "(" [ exp { "," exp }] ")"
	| lvalue "." id "(" [ exp { "," exp }] ")"

	| "-" exp
	| exp op exp
	
	| assignation

	| "if" exp block [ "else" block ]
	| "while" "(" exp ")" block
	| "for" "(" [ vardec { ',' vardec } ] ";" [ exp ] ";" [ assignation { ',' assignation } ] ")" block
	| "break"
	| "return" [ exp ]

	| vardec

assignation = lvalue assignop exp

lvalue =
	id
	| lvalue "." id
	| lvalue "[" exp "]"
	;


number = i8 | i16 | i32 | i64 | u8 | u16 | u32 | u64
float = f32 | f64


op = 
	"+" | "-" | "*" | "/" 
	| "==" | "!=" | "<" | "<=" | "=>" | ">"
	| "!" | "&&" | "||"
	| "&" | "^" | "|" | "<<" | ">>" | "~"

assignop = "=" | "+=" | "-=" | "*=" | "/=" | "&=" | "|=" | "^=" | "<<=" | ">>=" | "~="

structdec = "struct" id "{" { struct_fields } "}" ";"

struct_fields =
	| ty id ";" [ struct_fields ]

vardec = ty id "=" exp ";" ;

fundec = ty id "(" { tyfields } ")" funbody ;

funbody =
	"{" exps "}"
	| ";"


tydec = "class" id [ ":" id ] "{" classfields "}" ;

classfields = { classfield ";" }

classfield =
	vardec