program =
	vardec [ program ]
	functions [ program ]

block = '{' { stm } '}'

stm =
	vardec
	| "return" [ exp ] ";"
	| "break" ";"
	| "if" exp block [ "else" block ]
	| "while" "(" exp ")" block
	| "for" "(" [ vardec { ',' vardec } ] ";" [ exp ] ";" [ exp { "," exp } ] ")" block
	| exp ";" 
	;

exp =
	number
	| float

	| lvalue

	| id "(" [ exp { "," exp }] ")"   			// function call
	| lvalue "." id "(" [ exp { "," exp }] ")"  // methode call

	| "-" exp | "!" exp                                // 
	| exp op exp
	
	| assignation
	| block ;


assignation = lvalue assignop exp ;

lvalue =
	id
	| lvalue "." id
	| lvalue "[" exp "]"
	;


number = i8 | i16 | i32 | i64 | u8 | u16 | u32 | u64
float = f32 | f64


op = 
	"+" | "-" | "*" | "/" 
	| "==" | "!=" | "<" | "<=" | "=>" | ">"
	| "!" | "&&" | "||"
	| "&" | "^" | "|" | "<<" | ">>" | "~"

assignop = "=" | "+=" | "-=" | "*=" | "/=" | "&=" | "|=" | "^=" | "<<=" | ">>=" | "~="

exp    = exp ("==" | "!=" | "<" | ...") sum | sum
sum    = sum ("+" | "-") term | term
term   = term ("*" | "/") unary | unary
unary  = "-" unary | "!" unary | primary
primary = 
	number 
	| float 
	| lvalue 
	| "(" exp ")"
    | id "(" [ exp { "," exp } ] ")"

structdec = "struct" id "{" { struct_fields } "}" ";"

struct_fields =
	| ty id ";" [ struct_fields ]

vardec = ty id [ "=" exp ] ";" ;

fundec = ty id "(" { tyfields } ")" funbody ;

funbody =
	block
	| ";"


tydec = "class" id [ ":" id ] "{" classfields "}" ;

classfields = { classfield ";" }

classfield =
	vardec